# Download / stage Windows tool binaries into vendor\windows\tools
# Run on Windows (or in GitHub Actions windows-latest).
#
# Produces: xroar.exe, lwasm.exe, decb.exe
#   xroar  — official XRoar w64 zip
#   lwasm  — official LWTOOLS win64 zip
#   decb   — prebuilt MinGW binary from CoCoIDE releases, or local incoming/

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
Set-Location $Root

$Out = Join-Path $Root "vendor\windows\tools"
$Cache = Join-Path $Root "vendor\windows\cache"
New-Item -ItemType Directory -Force -Path $Out, $Cache | Out-Null

$XroarVer = if ($env:COCOIDE_XROAR_WIN_VER) { $env:COCOIDE_XROAR_WIN_VER } else { "1.11" }
$LwtoolsVer = if ($env:COCOIDE_LWTOOLS_WIN_VER) { $env:COCOIDE_LWTOOLS_WIN_VER } else { "4.25" }
$XroarUrl = "https://www.6809.org.uk/xroar/dl/xroar-$XroarVer-w64.zip"
$LwtoolsUrl = "https://www.lwtools.ca/releases/lwtools/lwtools-$LwtoolsVer-win64.zip"
# Prebuilt PE from CoCoIDE releases (MinGW cross-build of Toolshed)
$DecbUrl = if ($env:COCOIDE_DECB_WIN_URL) {
    $env:COCOIDE_DECB_WIN_URL
} else {
    "https://github.com/alexgayer85/CoCoIDE/releases/download/v0.1.0/decb-windows-x86_64.exe"
}

function Get-ZipAndFind([string]$Url, [string]$ZipPath, [string]$Pattern) {
    if (-not (Test-Path $ZipPath)) {
        Write-Host "Downloading $Url"
        Invoke-WebRequest -Uri $Url -OutFile $ZipPath -UseBasicParsing
    }
    $extract = Join-Path $Cache ([IO.Path]::GetFileNameWithoutExtension($ZipPath) + "-extract")
    if (Test-Path $extract) { Remove-Item -Recurse -Force $extract }
    Expand-Archive -Path $ZipPath -DestinationPath $extract -Force
    $hit = Get-ChildItem -Path $extract -Recurse -Filter $Pattern | Select-Object -First 1
    if (-not $hit) { throw "Could not find $Pattern in $ZipPath" }
    return $hit.FullName
}

Write-Host "==> XRoar $XroarVer"
$xroar = Get-ZipAndFind $XroarUrl (Join-Path $Cache "xroar-$XroarVer-w64.zip") "xroar.exe"
Copy-Item -Force $xroar (Join-Path $Out "xroar.exe")

Write-Host "==> LWTOOLS $LwtoolsVer"
$lwasm = Get-ZipAndFind $LwtoolsUrl (Join-Path $Cache "lwtools-$LwtoolsVer-win64.zip") "lwasm.exe"
Copy-Item -Force $lwasm (Join-Path $Out "lwasm.exe")

Write-Host "==> Toolshed decb.exe"
$decbOut = Join-Path $Out "decb.exe"
$incoming = Join-Path $Root "vendor\windows\incoming\decb.exe"
if (Test-Path $incoming) {
    Write-Host "Using $incoming"
    Copy-Item -Force $incoming $decbOut
} elseif (Test-Path $decbOut) {
    Write-Host "Keeping existing $decbOut"
} else {
    Write-Host "Downloading $DecbUrl"
    Invoke-WebRequest -Uri $DecbUrl -OutFile $decbOut -UseBasicParsing
}
if (-not (Test-Path $decbOut)) { throw "decb.exe missing after fetch" }

@(
    "# Generated by fetch_tools_windows.ps1 on $(Get-Date -Format o)"
    "xroar.exe  $XroarUrl"
    "lwasm.exe  $LwtoolsUrl"
    "decb.exe   $DecbUrl (or local)"
    (Get-ChildItem $Out\*.exe | ForEach-Object { $_.Name + " " + $_.Length })
) | Set-Content -Path (Join-Path $Out "VERSIONS.txt") -Encoding UTF8

Write-Host "Staged tools in $Out"
Get-ChildItem $Out
