# Download / stage Windows tool binaries into vendor\windows\tools
# Run on Windows (or in GitHub Actions windows-latest).
#
# Produces: xroar.exe, lwasm.exe, and uses decb.exe if already present
# (build Toolshed in MSYS2 first — see .github/workflows/windows-pyinstaller.yml).

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
Set-Location $Root

$Out = Join-Path $Root "vendor\windows\tools"
$Cache = Join-Path $Root "vendor\windows\cache"
New-Item -ItemType Directory -Force -Path $Out, $Cache | Out-Null

$XroarVer = if ($env:COCOIDE_XROAR_WIN_VER) { $env:COCOIDE_XROAR_WIN_VER } else { "1.11" }
$LwtoolsVer = if ($env:COCOIDE_LWTOOLS_WIN_VER) { $env:COCOIDE_LWTOOLS_WIN_VER } else { "4.25" }
$XroarUrl = "https://www.6809.org.uk/xroar/dl/xroar-$XroarVer-w64.zip"
$LwtoolsUrl = "https://www.lwtools.ca/releases/lwtools/lwtools-$LwtoolsVer-win64.zip"

function Get-ZipAndFind([string]$Url, [string]$ZipPath, [string]$Pattern) {
    if (-not (Test-Path $ZipPath)) {
        Write-Host "Downloading $Url"
        Invoke-WebRequest -Uri $Url -OutFile $ZipPath -UseBasicParsing
    }
    $extract = Join-Path $Cache ([IO.Path]::GetFileNameWithoutExtension($ZipPath) + "-extract")
    if (Test-Path $extract) { Remove-Item -Recurse -Force $extract }
    Expand-Archive -Path $ZipPath -DestinationPath $extract -Force
    $hit = Get-ChildItem -Path $extract -Recurse -Filter $Pattern | Select-Object -First 1
    if (-not $hit) { throw "Could not find $Pattern in $ZipPath" }
    return $hit.FullName
}

Write-Host "==> XRoar $XroarVer"
$xroar = Get-ZipAndFind $XroarUrl (Join-Path $Cache "xroar-$XroarVer-w64.zip") "xroar.exe"
Copy-Item -Force $xroar (Join-Path $Out "xroar.exe")

Write-Host "==> LWTOOLS $LwtoolsVer"
$lwasm = Get-ZipAndFind $LwtoolsUrl (Join-Path $Cache "lwtools-$LwtoolsVer-win64.zip") "lwasm.exe"
Copy-Item -Force $lwasm (Join-Path $Out "lwasm.exe")

$decbOut = Join-Path $Out "decb.exe"
if (-not (Test-Path $decbOut)) {
    $incoming = Join-Path $Root "vendor\windows\incoming\decb.exe"
    if (Test-Path $incoming) {
        Copy-Item -Force $incoming $decbOut
    } else {
        throw @"
decb.exe missing at $decbOut

Build it first (MSYS2 UCRT64):
  git clone --depth 1 https://github.com/nitros9project/toolshed.git
  cd toolshed/build/unix
  make CC=gcc WIN=1 DIRS='libtoolshed libnative libcecb librbf libcoco libdecb libmisc libsys decb' all
  copy decb\decb.exe to vendor\windows\tools\decb.exe

Or place a pre-built binary at vendor\windows\incoming\decb.exe
The GitHub Actions workflow builds this automatically.
"@
    }
}

@(
    "# Generated by fetch_tools_windows.ps1 on $(Get-Date -Format o)"
    "xroar.exe  $XroarUrl"
    "lwasm.exe  $LwtoolsUrl"
    "decb.exe   $(if (Test-Path $decbOut) { (Get-Item $decbOut).Length } else { 'missing' }) bytes"
    (Get-ChildItem $Out\*.exe | ForEach-Object { $_.Name + " " + $_.Length })
) | Set-Content -Path (Join-Path $Out "VERSIONS.txt") -Encoding UTF8

Write-Host "Staged tools in $Out"
Get-ChildItem $Out
