#!/usr/bin/env bash
# Download / cross-build Windows tool binaries into vendor/windows/tools.
#
# Produces:
#   vendor/windows/tools/xroar.exe   (official XRoar w64 zip)
#   vendor/windows/tools/lwasm.exe   (official LWTOOLS win64 zip)
#   vendor/windows/tools/decb.exe    (Toolshed cross-built with MinGW)
#
# Requires: curl, unzip, make, x86_64-w64-mingw32-gcc (Debian/Ubuntu: mingw-w64)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${ROOT}/vendor/windows/tools"
CACHE="${ROOT}/vendor/windows/cache"
mkdir -p "$OUT" "$CACHE"

XROAR_VER="${COCOIDE_XROAR_WIN_VER:-1.11}"
LWTOOLS_VER="${COCOIDE_LWTOOLS_WIN_VER:-4.25}"
XROAR_URL="${COCOIDE_XROAR_WIN_URL:-https://www.6809.org.uk/xroar/dl/xroar-${XROAR_VER}-w64.zip}"
LWTOOLS_URL="${COCOIDE_LWTOOLS_WIN_URL:-https://www.lwtools.ca/releases/lwtools/lwtools-${LWTOOLS_VER}-win64.zip}"
TOOLSHED_REPO="${COCOIDE_TOOLSHED_REPO:-https://github.com/nitros9project/toolshed.git}"

need() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "error: missing command: $1" >&2
    exit 1
  }
}

need curl
need unzip
need make
need git
need x86_64-w64-mingw32-gcc

echo "==> Fetching XRoar ${XROAR_VER} (Windows x64)"
XROAR_ZIP="${CACHE}/xroar-${XROAR_VER}-w64.zip"
if [[ ! -f "$XROAR_ZIP" ]]; then
  curl -fsSL -o "$XROAR_ZIP" "$XROAR_URL"
fi
rm -rf "${CACHE}/xroar-extract"
mkdir -p "${CACHE}/xroar-extract"
unzip -q -o "$XROAR_ZIP" -d "${CACHE}/xroar-extract"
XROAR_EXE="$(find "${CACHE}/xroar-extract" -type f -iname 'xroar.exe' | head -1)"
[[ -n "$XROAR_EXE" ]] || { echo "error: xroar.exe not in $XROAR_URL" >&2; exit 1; }
cp -f "$XROAR_EXE" "$OUT/xroar.exe"
# Optional GPL text from the zip
XROAR_COPY="$(find "${CACHE}/xroar-extract" -type f -iname 'COPYING*' | head -1 || true)"
if [[ -n "$XROAR_COPY" ]]; then
  cp -f "$XROAR_COPY" "$OUT/COPYING-XRoar.txt"
fi

echo "==> Fetching LWTOOLS ${LWTOOLS_VER} (Windows x64)"
LW_ZIP="${CACHE}/lwtools-${LWTOOLS_VER}-win64.zip"
if [[ ! -f "$LW_ZIP" ]]; then
  curl -fsSL -o "$LW_ZIP" "$LWTOOLS_URL"
fi
rm -rf "${CACHE}/lwtools-extract"
mkdir -p "${CACHE}/lwtools-extract"
unzip -q -o "$LW_ZIP" -d "${CACHE}/lwtools-extract"
LWASM_EXE="$(find "${CACHE}/lwtools-extract" -type f -iname 'lwasm.exe' | head -1)"
[[ -n "$LWASM_EXE" ]] || { echo "error: lwasm.exe not in $LWTOOLS_URL" >&2; exit 1; }
cp -f "$LWASM_EXE" "$OUT/lwasm.exe"

echo "==> Cross-building Toolshed decb.exe (MinGW)"
TS_SRC="${CACHE}/toolshed-src"
if [[ ! -d "${TS_SRC}/.git" ]]; then
  rm -rf "$TS_SRC"
  git clone --depth 1 "$TOOLSHED_REPO" "$TS_SRC"
else
  git -C "$TS_SRC" pull --ff-only || true
fi
# Build only decb (and libs) with WIN=1 — faster than full winpackage
(
  cd "${TS_SRC}/build/unix"
  make cleandirs >/dev/null 2>&1 || true
  # Ensure winpackage-style flags
  make -j"$(nproc 2>/dev/null || echo 2)" CC=x86_64-w64-mingw32-gcc WIN=1 \
    DIRS="libtoolshed libnative libcecb librbf libcoco libdecb libmisc libsys decb" \
    all
)
DECB_EXE="${TS_SRC}/build/unix/decb/decb.exe"
[[ -f "$DECB_EXE" ]] || { echo "error: decb.exe build failed" >&2; exit 1; }
cp -f "$DECB_EXE" "$OUT/decb.exe"

# Version stamp
{
  echo "# Generated by scripts/fetch_tools_windows.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "xroar.exe  source=${XROAR_URL}"
  echo "lwasm.exe  source=${LWTOOLS_URL}"
  echo "decb.exe   Toolshed MinGW cross-build from ${TOOLSHED_REPO}"
  if [[ -f "${TS_SRC}/build/unix/rules.mak" ]]; then
    grep -E 'VERSION' "${TS_SRC}/build/unix/rules.mak" | head -3 || true
  fi
  ls -la "$OUT"/*.exe
} > "$OUT/VERSIONS.txt"

echo "Staged Windows tools in $OUT"
cat "$OUT/VERSIONS.txt"
