#!/usr/bin/env bash
# Stage Windows tool binaries into vendor/windows/tools.
#
# This script expects you to place or download official/built EXEs:
#   - xroar.exe   from https://www.6809.org.uk/xroar/ (Windows zip)
#   - lwasm.exe   from https://www.lwtools.ca/ (e.g. lwtools-*-win64.zip)
#   - decb.exe    built with MSYS2/MinGW from Toolshed sources
#
# Usage:
#   # After downloading into vendor/windows/incoming/
#   ./scripts/fetch_tools_windows.sh
#
# Or set COCOIDE_WIN_TOOLS to a directory that already contains the three EXEs.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${ROOT}/vendor/windows/tools"
INCOMING="${COCOIDE_WIN_TOOLS:-${ROOT}/vendor/windows/incoming}"
mkdir -p "$OUT"

copy_one() {
  local name="$1"
  local src=""
  if [[ -f "${INCOMING}/${name}" ]]; then
    src="${INCOMING}/${name}"
  elif [[ -f "${INCOMING}/${name}.exe" ]]; then
    src="${INCOMING}/${name}.exe"
  else
    # search one level deep (zip extracts)
    src="$(find "$INCOMING" -type f \( -name "$name" -o -name "${name}.exe" \) 2>/dev/null | head -1 || true)"
  fi
  if [[ -z "$src" || ! -f "$src" ]]; then
    echo "error: could not find ${name}.exe under $INCOMING" >&2
    echo "Download XRoar / LWTOOLS / Toolshed Windows binaries and place them there." >&2
    exit 1
  fi
  cp -f "$src" "${OUT}/${name}.exe"
  echo "  ${name}.exe <- $src"
}

if [[ ! -d "$INCOMING" ]]; then
  echo "error: incoming dir missing: $INCOMING" >&2
  echo "Create it and add xroar.exe, decb.exe, lwasm.exe" >&2
  exit 1
fi

echo "Staging Windows tools from $INCOMING"
copy_one xroar
copy_one decb
copy_one lwasm

{
  echo "# Generated by scripts/fetch_tools_windows.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "xroar.exe staged"
  echo "decb.exe staged"
  echo "lwasm.exe staged"
  ls -la "$OUT"
} > "$OUT/VERSIONS.txt"

echo "Staged tools in $OUT"
