#!/usr/bin/env bash
# Copy or stage Linux tool binaries into vendor/linux/tools for packaging.
# Dev convenience: uses tools already on PATH. For reproducible CI, prefer
# building from pinned sources (see packaging/versions.lock).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${ROOT}/vendor/linux/tools"
mkdir -p "$OUT"

need() {
  local name="$1"
  if ! command -v "$name" >/dev/null 2>&1; then
    echo "error: $name not found on PATH" >&2
    exit 1
  fi
}

need xroar
need decb
need lwasm

cp -f "$(command -v xroar)" "$OUT/xroar"
cp -f "$(command -v decb)"  "$OUT/decb"
cp -f "$(command -v lwasm)" "$OUT/lwasm"
chmod +x "$OUT/xroar" "$OUT/decb" "$OUT/lwasm"

{
  echo "# Generated by scripts/fetch_tools_linux.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo -n "xroar: "
  "$OUT/xroar" --version 2>&1 | head -1 || true
  echo -n "lwasm: "
  "$OUT/lwasm" --version 2>&1 | head -1 || true
  echo -n "decb: "
  # decb has no --version; parse banner from help
  "$OUT/decb" 2>&1 | head -3 | tr '\n' ' '
  echo
} > "$OUT/VERSIONS.txt"

echo "Staged tools in $OUT"
cat "$OUT/VERSIONS.txt"
